# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

---
- name: Check for composer.phar
  stat:
    path: "{{ composer_path }}"
  register: composer_file

- name: Run composer self-update
  shell: "{{ composer_path }} selfupdate --no-interaction"
  when: composer_file.stat.exists
  register: composer_self_update_result
  changed_when: composer_self_update_result.stderr | search('Updating')

- name: Install composer
  get_url:
    url: https://getcomposer.org/composer.phar
    dest: "{{ composer_path }}"
    mode: 0755
    validate_certs: no
    force: no

- name: Run composer install task manager
  shell: "{{ php_path }} {{ composer_path }} install -o --no-dev --no-interaction"
  args:
      chdir: "{{ ansistrano_release_path.stdout }}/TaskManager"
  register: composer_install_result
  changed_when: composer_install_result.stderr | search('- \w+ing ')

- name: Run composer install identity access
  shell: "{{ php_path }} {{ composer_path }} install -o --no-dev --no-interaction"
  args:
      chdir: "{{ ansistrano_release_path.stdout }}/IdentityAccess"
  register: composer_install_result
  changed_when: composer_install_result.stderr | search('- \w+ing ')

- name: Run composer install notifier
  shell: "{{ php_path }} {{ composer_path }} install -o --no-dev --no-interaction"
  args:
      chdir: "{{ ansistrano_release_path.stdout }}/Notifier"
  register: composer_install_result
  changed_when: composer_install_result.stderr | search('- \w+ing ')
