# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Kreta\Component\Project\Model\Participant:
    type: entity
    repositoryClass: Kreta\Component\Project\Repository\ParticipantRepository
    table: participant
    id:
        project:
            type: entity
            associationKey: true
        user:
            type: entity
            associationKey: true
    fields:
        role:
            type: string
            length: 20
    manyToOne:
        project:
            targetEntity: Kreta\Component\Project\Model\Interfaces\ProjectInterface
            inversedBy: participants
            joinColumn:
                name: project_id
                referencedColumnName: id
                onDelete: CASCADE
        user:
            targetEntity: Kreta\Component\User\Model\Interfaces\UserInterface
            joinColumn:
                name: user_id
                referencedColumnName: id
                onDelete: CASCADE
