/*
 * This file is part of the Kreta package.
 *
 * (c) Beñat Espiña <benatespina@gmail.com>
 * (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

const ActionTypes = {
  CHANGE_EVENT: 'CHANGE_EVENT',

  MAIN_MENU_SHOW_PROJECTS: 'MAIN_MENU_SHOW_PROJECTS',
  MAIN_MENU_HIDE_PROJECTS: 'MAIN_MENU_HIDE_PROJECTS',
  MAIN_MENU_HIGHLIGHT_PROJECT: 'MAIN_MENU_HIGHLIGHT_PROJECT',

  USER_AUTHORIZING: 'USER_AUTHORIZING',
  USER_AUTHORIZED: 'USER_AUTHORIZED',
  USER_UNAUTHORIZING: 'USER_UNAUTHORIZING',
  USER_UNAUTHORIZED: 'USER_UNAUTHORIZED',
  USER_AUTHORIZATION_ERROR: 'USER_AUTHORIZATION_ERROR',

  USER_REQUESTING_RESET_PASSWORD: 'USER_REQUESTING_RESET_PASSWORD',
  USER_REQUESTED_RESET_PASSWORD: 'USER_REQUESTING_RESET_PASSWORD',

  USER_RESETTING_PASSWORD: 'USER_RESETTING_PASSWORD',
  USER_RESTORED_PASSWORD: 'USER_RESTORED_PASSWORD',
  USER_RESET_PASSWORD_ERROR: 'USER_RESET_PASSWORD_ERROR',

  USER_REGISTERING: 'USER_REGISTERING',
  USER_REGISTER: 'USER_REGISTER',
  USER_REGISTERED: 'USER_REGISTERED',
  USER_REGISTER_ERROR: 'USER_REGISTER_ERROR',

  USER_ENABLING: 'USER_ENABLING',
  USER_ENABLE: 'USER_ENABLE',
  USER_ENABLED: 'USER_ENABLED',
  USER_ENABLE_ERROR: 'USER_ENABLE_ERROR',

  PROFILE_FETCHING: 'PROFILE_FETCHING',
  PROFILE_RECEIVED: 'PROFILE_RECEIVED',
  PROFILE_FETCH_ERROR: 'PROFILE_FETCH_ERROR',

  PROFILE_UPDATE: 'PROFILE_UPDATE',
  PROFILE_UPDATED: 'PROFILE_UPDATED',
  PROFILE_UPDATE_ERROR: 'PROFILE_UPDATE_ERROR',

  PROJECTS_FETCHING: 'PROJECTS_FETCHING',
  PROJECTS_FETCH_ERROR: 'PROJECTS_FETCH_ERROR',
  PROJECTS_RECEIVED: 'PROJECTS_RECEIVED',

  PROJECTS_CREATING: 'PROJECTS_CREATING',
  PROJECTS_CREATED: 'PROJECTS_CREATED',
  PROJECTS_CREATE_ERROR: 'PROJECTS_CREATE_ERROR',

  CURRENT_ORGANIZATION_FETCHING: 'CURRENT_ORGANIZATION_FETCHING',
  CURRENT_ORGANIZATION_RECEIVED: 'CURRENT_ORGANIZATION_RECEIVED',

  CURRENT_PROJECT_FETCHING: 'CURRENT_PROJECT_FETCHING',
  CURRENT_PROJECT_RECEIVED: 'CURRENT_PROJECT_RECEIVED',
  CURRENT_PROJECT_TASK_FILTERS_LOADED: 'CURRENT_PROJECT_TASK_FILTERS_LOADED',
  CURRENT_PROJECT_TASKS_RECEIVED: 'CURRENT_PROJECT_TASKS_RECEIVED',
  CURRENT_PROJECT_UPDATE: 'PROJECT_UPDATE',
  CURRENT_PROJECT_UPDATED: 'CURRENT_PROJECT_UPDATED',
  CURRENT_PROJECT_UPDATE_ERROR: 'CURRENT_PROJECT_UPDATE_ERROR',
  CURRENT_PROJECT_SELECTED_TASK_FETCHING: 'CURRENT_PROJECT_SELECTED_TASK_FETCHING',
  CURRENT_PROJECT_SELECTED_TASK_CHANGED: 'CURRENT_PROJECT_SELECTED_TASK_CHANGED',
  CURRENT_PROJECT_TASK_CREATING: 'CURRENT_PROJECT_TASK_CREATING',
  CURRENT_PROJECT_TASK_CREATED: 'CURRENT_PROJECT_TASK_CREATED',
  CURRENT_PROJECT_TASK_CREATE_ERROR: 'CURRENT_PROJECT_TASK_CREATE_ERROR',
  CURRENT_PROJECT_TASK_UPDATE: 'CURRENT_PROJECT_TASK_UPDATE',
  CURRENT_PROJECT_TASK_UPDATED: 'CURRENT_PROJECT_TASK_UPDATED',
  CURRENT_PROJECT_TASK_UPDATE_ERROR: 'CURRENT_PROJECT_TASK_UPDATE_ERROR',
  CURRENT_PROJECT_TASK_FILTERING: 'CURRENT_PROJECT_TASK_FILTERING',
  CURRENT_PROJECT_TASK_FILTERED: 'CURRENT_PROJECT_TASK_FILTERED',

  NOTIFICATION_REMOVE_OLD: 'NOTIFICATION_REMOVE_OLD',
  NOTIFICATION_REMOVING: 'NOTIFICATION_REMOVING',
  NOTIFICATION_REMOVE: 'NOTIFICATION_REMOVE',

  ORGANIZATION_CREATING: 'ORGANIZATION_CREATING',
  ORGANIZATION_CREATED: 'ORGANIZATION_CREATED',
  ORGANIZATION_CREATE_ERROR: 'ORGANIZATION_CREATE_ERROR',

  DASHBOARD_DATA_FETCHING: 'DASHBOARD_DATA_FETCHING',
  DASHBOARD_DATA_RECEIVED: 'DASHBOARD_DATA_RECEIVED',
  DASHBOARD_DATA_FETCH_ERROR: 'DASHBOARD_DATA_FETCH_ERROR'
};

export default ActionTypes;
