/*
 * This file is part of the Kreta package.
 *
 * (c) Beñat Espiña <benatespina@gmail.com>
 * (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

const ActionTypes = {
  CHANGE_EVENT: 'CHANGE_EVENT',

  MAIN_MENU_SHOW_PROJECTS: 'MAIN_MENU_SHOW_PROJECTS',
  MAIN_MENU_HIDE_PROJECTS: 'MAIN_MENU_HIDE_PROJECTS',
  MAIN_MENU_HIGHLIGHT_PROJECT: 'MAIN_MENU_HIGHLIGHT_PROJECT',

  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',

  PROFILE_FETCHING: 'PROFILE_FETCHING',
  PROFILE_RECEIVED: 'PROFILE_RECEIVED',
  PROFILE_FETCH_ERROR: 'PROFILE_FETCH_ERROR',

  PROFILE_UPDATE: 'PROFILE_UPDATE',
  PROFILE_UPDATED: 'PROFILE_UPDATED',
  PROFILE_UPDATE_ERROR: 'PROFILE_UPDATE_ERROR',

  PROJECTS_FETCHING: 'PROJECTS_FETCHING',
  PROJECTS_FETCH_ERROR: 'PROJECTS_FETCH_ERROR',
  PROJECTS_RECEIVED: 'PROJECTS_RECEIVED',
  PROJECTS_CREATING: 'PROJECTS_CREATING',
  PROJECTS_CREATED: 'PROJECTS_CREATED',
  PROJECTS_CREATE_ERROR: 'PROJECTS_CREATE_ERROR',

  CURRENT_PROJECT_FETCHING: 'CURRENT_PROJECT_FETCHING',
  CURRENT_PROJECT_RECEIVED: 'CURRENT_PROJECT_RECEIVED',
  CURRENT_PROJECT_ISSUES_RECEIVED: 'CURRENT_PROJECT_ISSUES_RECEIVED',
  CURRENT_PROJECT_UPDATE: 'PROJECT_UPDATE',
  CURRENT_PROJECT_UPDATED: 'CURRENT_PROJECT_UPDATED',
  CURRENT_PROJECT_UPDATE_ERROR: 'CURRENT_PROJECT_UPDATE_ERROR',
  CURRENT_PROJECT_SELECTED_ISSUE_FETCHING: 'CURRENT_PROJECT_SELECTED_ISSUE_FETCHING',
  CURRENT_PROJECT_SELECTED_ISSUE_CHANGED: 'CURRENT_PROJECT_SELECTED_ISSUE_CHANGED',
  CURRENT_PROJECT_ISSUE_CREATING: 'CURRENT_PROJECT_ISSUE_CREATING',
  CURRENT_PROJECT_ISSUE_CREATED: 'CURRENT_PROJECT_ISSUE_CREATED',
  CURRENT_PROJECT_ISSUE_CREATE_ERROR: 'CURRENT_PROJECT_ISSUE_CREATE_ERROR',
  CURRENT_PROJECT_ISSUE_UPDATE: 'CURRENT_PROJECT_ISSUE_UPDATE',
  CURRENT_PROJECT_ISSUE_UPDATED: 'CURRENT_PROJECT_ISSUE_UPDATED',
  CURRENT_PROJECT_ISSUE_UPDATE_ERROR: 'CURRENT_PROJECT_ISSUE_UPDATE_ERROR',
  CURRENT_PROJECT_ISSUE_FILTERING: 'CURRENT_PROJECT_ISSUE_FILTERING',
  CURRENT_PROJECT_ISSUE_FILTERED: 'CURRENT_PROJECT_ISSUE_FILTERED',

  NOTIFICATION_REMOVE_OLD: 'NOTIFICATION_REMOVE_OLD',
  NOTIFICATION_REMOVE: 'NOTIFICATION_REMOVE'
};

export default ActionTypes;
